[functions]
node_bundler = "esbuild"
directory = "/"
included_files = [
    "assets/**",
    "controllers/**",
    "helpers/**",
    "public/**",
    "routes/**",
    "views/**",
    "app.js",
    "env.js"
]

[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/api/:splat"